# Generated by Django 2.1 on 2019-06-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_image', models.ImageField(upload_to='layer_image')),
            ],
            options={
                'verbose_name_plural': 'Layer images',
            },
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='upload_image'),
        ),
    ]
