# Generated by Django 2.1 on 2019-06-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_image', '0002_auto_20190625_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='tfkerasModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfkerasModel', models.CharField(choices=[(1, 'vgg16'), (2, 'vgg19')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'tfkerasModel',
            },
        ),
    ]
