# Generated by Django 2.1 on 2019-06-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_image', '0003_tfkerasmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfkerasmodel',
            name='tfkerasModel',
            field=models.CharField(choices=[(1, 'tf.keras.applications.densenet'), (2, 'tf.keras.applications.inception_resnet_v2'), (3, 'tf.keras.applications.inception_v3'), (4, 'tf.keras.applications.mobilenet'), (5, 'tf.keras.applications.mobilenet_v2'), (6, 'tf.keras.applications.nasnet'), (7, 'tf.keras.applications.resnet50'), (8, 'tf.keras.applications.vgg16'), (9, 'tf.keras.applications.vgg19'), (10, 'tf.keras.applications.xception')], max_length=50),
        ),
    ]
