# Generated by Django 2.1 on 2019-06-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_image', '0004_auto_20190627_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfkerasmodel',
            name='tfkerasModel',
            field=models.CharField(choices=[('densenet', 'tf.keras.applications.densenet'), ('inception_resnet_v2', 'tf.keras.applications.inception_resnet_v2'), ('inception_v3', 'tf.keras.applications.inception_v3'), ('mobilenet', 'tf.keras.applications.mobilenet'), ('mobilenet_v2', 'tf.keras.applications.mobilenet_v2'), ('nasnet', 'tf.keras.applications.nasnet'), ('resnet50', 'tf.keras.applications.resnet50'), ('vgg16', 'tf.keras.applications.vgg16'), ('vgg19', 'tf.keras.applications.vgg19'), ('xception', 'tf.keras.applications.xception')], max_length=50),
        ),
    ]
